### ISSUE TITLE
Option not appearing in Camera Control

### ISSUE THREAD

**Issue by alexfoxy** [JuniperPhoton/LockedCameraCaptureExtensionDemo#2]
Heya, I'm trying to build an extension into my app, but I can't get the app to appear in the list of options for being openable by the camera control. What could I be missing?

**Comment by JuniperPhoton** [comment]
Hi. I suppose that once you have built your Capture Extension and made it work, it will appear in the list automatically and no other actions should be done.

**Comment by alexfoxy** [comment]
Are you selecting the extention from the build targets? i.e. from this list: 
<img width="252" alt="Screenshot 2024-09-30 at 13 27 02" src="https://github.com/user-attachments/assets/550d0131-cf0c-45a0-8e5f-084e7165efa7">

**Comment by JuniperPhoton** [comment]
The target to launch has nothing to do with the issue that your app is not listed in the Camera Control settings. However, if you can select your app in the Action Button settings by the "Control" page, it should also included in the Camera Control list. If it won't, maybe you can try forcing the system to refresh: change the system language to the other one and change it back.

**Comment by alexfoxy** [comment]
Hmm, ok I’ll try it. I added all the extensions from Apple’s guide but I can’t get it to appear in either the widget list or the camera control list.

**Comment by jaekong** [comment]
Personally, I had the same issue on my app. It was because I was using Swift Package to share common logic between the main app, the widget extension and the capture extension.

The source file that has the subclass of `CameraCaptureIntent` has to be inside the main app target's source directory. Apple made [`AppIntentsPackage`](https://developer.apple.com/documentation/appintents/appintentspackage) protocol to deal with this issue, but it doesn't work as of Xcode 16 and iOS 18.1 beta 6.

Apparently using framework, or anything similar also doesn't work - even if you added target membership (Swift Packages don't support traditional target membership so I couldn't check that.)

In my case, I just duplicated the same source code, one inside my App's target source directory, and the other inside the Swift Package (I couldn't just move it because some of the shared code inside the package depended on the Intent) and It works well. I added all the target memberships to the Intent source file on my App.

**Comment by jaekong** [comment]
@JuniperPhoton It would be very helpful if you can mention this problem on the README file. There's not a lot of resources on `LockedCameraCapture` as of now, and your project has helped me quite a lot on figuring out the problem. But also, it would be great if other people could just skip to the solution.

**Comment by JuniperPhoton** [comment]
@jaekong Thanks. I totally ignore the case where the subclass of `CameraCaptureIntent` will be discovered by the system and should be in the main bundle. 

I haven't discovered the [AppIntentsPackage](https://developer.apple.com/documentation/appintents/appintentspackage) protocol, but according to its description, it seems to resolve this kind of issue, which I may try later.

**Comment by jaekong** [comment]
@JuniperPhoton It should, but sadly it seems like it doesn't work.

https://forums.developer.apple.com/forums/thread/732535

**Comment by JuniperPhoton** [comment]
The README has been updated with section of "Additional Information" about the ``CameraCaptureIntent``.

**Comment by nj-bss** [comment]
Hi @JuniperPhoton,
I have created the UIKit based app and followed your app to list my app under the Settings -> Camera -> Camera Control.
Created extension and widget too, unfortunately, my app is not listed in the Settings. Is there anything that I am missing.

**Comment by JuniperPhoton** [comment]
Hi. Did you check the information provided by other fellows above?

If this can't be resolved after some methods like restarting your device or changing languages back and forth (which will force the system to refresh some components), it may be the issue where you put your `AppIntent` implementation outside of your main target. 

For example, dynamically linking your `AppIntent` implementation via a Swift Package may cause this issue, and if I remember correctly, this is "fixed" by Apple starting iOS 26.

**Comment by nj-bss** [comment]
Thanks for the quick reply @JuniperPhoton, as of now there is no use of `AppIntent ` in my app. The idea is to have a main screen with a camera feature and have my app listed under the Settings -> Camera -> Camera Control. User can see that option and enable, but currently it is not showing.

**Comment by JuniperPhoton** [comment]
I think your implementation of `CameraCaptureIntent` is a must-have, if you want your app to be listed in that page.

**Comment by nj-bss** [comment]
I will give it a try then.

**Comment by nj-bss** [comment]
Thanks @JuniperPhoton, I am able to list my app and open the camera view by pressing the Camera Control button. However, I found new issue that the system kills and close the view after ~10 seconds. Do you know how to overcome this issue?

**Comment by JuniperPhoton** [comment]
@nj-bss You can check on my other post about this: https://juniperphoton.substack.com/p/addressing-unexpected-terminations?utm_source=publication-search

**Comment by nj-bss** [comment]
Thanks, @JuniperPhoton. This helped keep the extension alive when the device is locked. How did you solve the app termination issue when the device is unlocked, and when you click the camera control, it launches the main app? I tried to find out in your above link,  but couldn't.

**Comment by JuniperPhoton** [comment]
If currently the device is locked, when pressing the Camera Control, it will just launch the capture extension (as a new process). And since your app is a camera app and will use the camera feature immediately (I assume your apps does the same thing), it should be fine and won't be terminated by the system.

**Comment by nj-bss** [comment]
Yes, I understand that it launches the capture extension when the device is locked, and it launches the main app when the device is unlocked. The issue is, the system kills it after ~10 seconds. I have gone through your [article](https://juniperphoton.substack.com/p/addressing-unexpected-terminations), but couldn't find the solution to keep the app alive. Just a message in the debugger: `Message from debugger: Terminated due to signal 9`

**Comment by JuniperPhoton** [comment]
What's the exact case when your app is terminated by the system after 10 seconds? Note: even if your device is unlocked (after verifying your Face ID), as long as you are in the lock screen, iOS will choose to launch the Capture Extension instead of the main app. This rule applies if you press the bottom control item to try to launch the app.

**Comment by nj-bss** [comment]
Yes, it launches the Capture Extension when the device is in the locked state. And, it launches the main app when the device is unlocked. In my case, there is a camera view on the home screen(it moves from splash screen -> Scene Delegate -> Tabbar). I noticed that it is killed by the system, whether you do any interaction(activity) or not.

**Comment by JuniperPhoton** [comment]
By saying "Camera View", do you actually setup an active camera session?

**Comment by nj-bss** [comment]
Yes, by Camera View I meant an active `AVCaptureSession`. In my implementation, the view (`QRScannerView`) configures a session with `AVCaptureDeviceInput` (video), adds `AVCaptureMetadataOutput` / `AVCaptureVideoDataOutput`, and attaches an `AVCaptureVideoPreviewLayer` to the view. The session is started with `session.startRunning()`, so it’s a live camera feed rather than a static UI.

**Comment by JuniperPhoton** [comment]
Did you also set up the `AVCaptureEventInteraction`? This's also a required and mentioned by [Apple](https://developer.apple.com/documentation/lockedcameracapture/creating-a-camera-experience-for-the-lock-screen). 

> The app extension terminates shortly after launch if it doesn’t have an active camera view that uses [AVCaptureEventInteraction](https://developer.apple.com/documentation/AVKit/AVCaptureEventInteraction) to handle events from the hardware buttons, or if access to the camera hasn’t been requested.

**Comment by nj-bss** [comment]
Yes, I have set it up. To give you an example, I have also installed the capture event interactions when the session is active and the app is launched in unlocked state. This way, it keeps the session alive.

    `private func installCaptureEventInteraction() {
        guard #available(iOS 17.2, *) else { return }
        
        // Remove any previous interaction to avoid duplicates on re-entry
        scannerView.interactions
            .filter { $0 is AVCaptureEventInteraction }
            .forEach { scannerView.removeInteraction($0) }
        
        let interaction = AVCaptureEventInteraction { [weak self] event in
            guard let self = self else { return }
            
            switch event.phase {
            case .began:
                print("Camera control pressed")
                // onPressCapture logic
                if !self.scannerView.isAnimating {
                    self.scannerView.startRunning()
                }
            case .ended:
                print("Camera control released")
            default:
                break
            }
        }
        
        scannerView.addInteraction(interaction)
        self.captureEventInteraction = interaction
    }`

The problem is, when the view controller is active in the Tabbar other than the camera view and I press the camera control button, there will be no active camera session, and the system will kill it.
I have checked the Instagram app, and it opens the camera view on top of any screen when launched by the camera control side button in the unlocked state. Do you know how we can detect when the app is launched by the camera control button? So, that can do the same thing like opening/moving to the camera view.

**Comment by JuniperPhoton** [comment]
I think this is the exact situation where my blog is talking about. As long as you launch the app through Camera Control, the system expects to have an active camera session, regardless of whether it's the user’s intention. 

To put it in other words, you should **trick** the system by setting up a camera session, and then end it at some time (for me, it's 0.5 seconds). When it's launched by the Camera Control, the `perform()` method in your own implementation of CameraCaptureIntent will be invoked, and you must figure out a proper approach to notify your app to do the trick.

**Comment by nj-bss** [comment]
Yes, I have tried that trick. Starting a session for 0.5 seconds and then stopping it does nothing. I mean, it kills the session. Another workaround is to store some flag in `UserDefaults` and get it in `sceneDidBecomeActive` and set the rootViewController again.

**Comment by JuniperPhoton** [comment]
If this trick can't work, may be there are some cases I don't know about. Sorry you have to figure this out by yourself.

**Comment by JuniperPhoton** [comment]
I have encountered the similar issue when using iOS 26. And I find that in addition to launch the camera session, we also need to hide a UIView to add the interaction like this:

```
@available(iOS 18, *)
private struct ProtectTerminatedFromCameraIntentUIViewRepresentable: UIViewRepresentable {
    func makeUIView(context: Self.Context) -> some UIView {
        let uiView = UIView()
        let interaction = AVCaptureEventInteraction { _ in
            // ignored
        }
        uiView.addInteraction(interaction)
        return uiView
    }
    
    func updateUIView(_ view: Self.UIViewType, context: Self.Context) {
        // ignored
    }
}
```

Then add this ProtectTerminatedFromCameraIntentUIViewRepresentable to your SwiftUI view.
